#pragma once
#ifndef AHRI_ASUKA_INFERENCE_BACKEND__ONNXRUNTIME_HPP
#define AHRI_ASUKA_INFERENCE_BACKEND__ONNXRUNTIME_HPP

#include <onnxruntime_cxx_api.h>

#endif // !AHRI_ASUKA_INFERENCE_BACKEND__ONNXRUNTIME_HPP
